web:
  restart: always
  build: .
  expose:
    - "8000"
  volumes:
    - /static
    - /home/docker/code/
nginx:
  dockerfile: nginx.Dockerfile
  build: .
  ports:
    - "80:80"
  links:
    - web:web
  volumes:
    - /www/static
  volumes_from:
    - web
